# Generated by Django 6.0.1 on 2026-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(choices=[('NONE', 'Unassigned'), ('NETWORK', 'Network & Security'), ('DB', 'Database Administration'), ('SERVER', 'Server & Cloud'), ('DEV', 'Software Development')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEPARTMENT', 'Department User'), ('DIT', 'Project Manager'), ('SDC', 'SDC Staff'), ('OFFICER', 'Officer')], max_length=20),
        ),
    ]
