# Generated by Django 5.2.10 on 2026-01-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_department_name_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department_name',
            field=models.CharField(blank=True, choices=[('IT Dept', 'IT Dept'), ('Cisco Dept', 'Cisco Dept')], max_length=100, null=True),
        ),
    ]
