# Generated by Django 5.2.10 on 2026-01-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_department_remove_user_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department_name',
            field=models.CharField(blank=True, choices=[('', 'None'), ('IT Dept', 'IT Dept'), ('Cisco Dept', 'Cisco Dept')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
