# Generated by Django 5.2.10 on 2026-01-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_user_department_user_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(choices=[('NONE', 'Unassigned'), ('NETWORK', 'Network & Security'), ('DB', 'Database Administration'), ('SERVER', 'Server & Cloud'), ('DEV', 'Software Development')], default='NONE', max_length=20),
        ),
    ]
