# Generated by Django 5.2.10 on 2026-01-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_user_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEPARTMENT', 'Department User'), ('DIT', 'Project Manager'), ('SDC', 'SDC Staff'), ('OFFICER', 'Officer')], max_length=20),
        ),
    ]
