# Generated by Django 5.2.10 on 2026-01-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department_name',
            field=models.CharField(choices=[('', 'None'), ('IT Dept', 'IT Dept'), ('Cisco Dept', 'Cisco Dept')], default='NONE', max_length=100),
        ),
    ]
