# Generated by Django 6.0.1 on 2026-01-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_domain_alter_user_role'),
        ('login', '0010_alter_user_department_name'),
    ]

    operations = [
    ]
