# Generated by Django 5.2.10 on 2026-01-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1 - 30 Minutes'), ('P2', 'P2 - 2 Hours'), ('P3', 'P3 - 1 Day'), ('P4', 'P4 - 2 Days')], default='P3', max_length=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_time',
            field=models.DurationField(blank=True, help_text='SLA duration based on priority', null=True),
        ),
    ]
