# Generated by Django 6.0.1 on 2026-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='domain',
            field=models.CharField(choices=[('NONE', 'Unassigned'), ('NETWORK', 'Network & Security'), ('DB', 'Database Administration'), ('SERVER', 'Server & Cloud'), ('DEV', 'Software Development')], default='NONE', max_length=20),
        ),
    ]
