# Generated by Django 5.2.10 on 2026-01-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='domain',
            field=models.CharField(choices=[('NONE', 'Unassigned'), ('NETWORK', 'Network & Security'), ('DB', 'Database Administration'), ('SERVER', 'Server & Cloud'), ('DEV', 'Software Development')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pm_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketauditlog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
