# Generated by Django 6.0.1 on 2026-01-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pm_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
