# Generated by Django 6.0.1 on 2026-01-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_department_domain_alter_user_department_name_and_more'),
        ('tickets', '0003_requesttype_tickettype_ticket_affected_end_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.domain'),
        ),
    ]
