# Generated by Django 6.0.1 on 2026-01-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_attachment_ticket_pm_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketauditlog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
