# Generated by Django 6.0.1 on 2026-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved by DIT'), ('REJECTED', 'Rejected by DIT'), ('IN_PROGRESS', 'In Progress (SDC)'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
    ]
