# Generated by Django 6.0.1 on 2026-01-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_attachment_ticket_domain_ticket_pm_remarks_and_more'),
        ('tickets', '0004_ticketauditlog_remarks'),
    ]

    operations = [
    ]
